import type { LpcSheet } from '../assets/lpc.generated';
import type { ItemId } from '../systems/items';
import type { Season, TimeState, Weather } from '../systems/time';
import type { AreaId } from '../world/areas';

/**
 * Everybody who lives in the valley.
 *
 * A union rather than a string, so a typo in a gift table or a schedule is a
 * compile error rather than a villager who silently never appears.
 */
export type NpcId = 'rowan' | 'maeve' | 'tobias' | 'juniper' | 'ash' | 'bram';

export type GiftReaction = 'loved' | 'liked' | 'neutral' | 'disliked' | 'hated';

/**
 * Where somebody is, for a stretch of one day.
 *
 * `season` and `weather` are the overrides: an entry that names either only
 * applies then, and entries are matched in list order, so the specific ones go
 * first and the everyday ones last. That ordering is the whole rule — there is
 * no scoring, no specificity table, and nothing to get subtly wrong.
 *
 * Hours are on the clock the day actually runs on, which starts at 6 and ends
 * at 26 rather than wrapping through midnight. See `scheduleHour`.
 */
export interface ScheduleEntry {
  season?: Season;
  weather?: Weather;
  /** Inclusive. */
  fromHour: number;
  /** Exclusive. */
  toHour: number;
  area: AreaId;
  /** Tile coordinates, converted to the centre of the tile when they walk. */
  x: number;
  y: number;
  /**
   * What they are doing here, in one word.
   *
   * Dialogue can key off it, so a line can be about the forge rather than
   * about the hour — which is the difference between a villager who has a
   * schedule and one who knows they have one.
   */
  activity: string;
}

/**
 * When a line is allowed to be said. Every field is optional and all of the
 * ones present must hold, so an entry with no conditions always matches — and
 * every villager is required to have one, which is what guarantees there is
 * always something to say.
 */
export interface DialogueCondition {
  minHearts?: number;
  maxHearts?: number;
  season?: Season;
  weather?: Weather;
  /** Only on their birthday. */
  birthday?: boolean;
  /** Only once the farm has finished, or been paid for, Rowan's quest. */
  questCompleted?: boolean;
  questRewarded?: boolean;
  /** Only while they are on a schedule entry with this activity. */
  activity?: string;
}

/**
 * A line, and when it earns the right to be said.
 *
 * A table rather than a tree: conditions on hearts, season, weather and the
 * hour cover everything this game needs, and the highest-priority match wins.
 * Branching conversation is a great deal more work and buys nothing here — what
 * makes a village feel alive is the right line at the right moment, not a menu.
 */
export interface DialogueEntry {
  /** Higher wins. Ties are broken by the day, so a tie rotates rather than sticks. */
  priority: number;
  when?: DialogueCondition;
  line: string;
}

export interface NpcDef {
  id: NpcId;
  name: string;
  /** Who they are, in one line, for the hover label. */
  blurb: string;
  /** The procedural sprite, used when the walk sheet is not loaded. */
  texture: string;
  /**
   * The LPC walk sheet they borrow, and the tint that tells them apart.
   *
   * The union comes from the art folder: it is every `*-sheet.png` that is
   * actually there, regenerated by `npm run lpc:manifest`. Today that is two
   * sheets and five villagers, so four of them are recoloured borrowings —
   * honest about what it is, and it means everybody walks instead of sliding.
   *
   * Giving one of them their own sheet is now a two-step job rather than a
   * four-step one: export from the LPC character generator, run
   * `npm run lpc:import -- <file> <name>-sheet --walkcycle`, then point `sheet`
   * at it and set `tint` back to `0xffffff`. The type will already know the
   * name exists.
   */
  sheet: LpcSheet;
  tint: number;
  birthday: { season: Season; day: number };
  /**
   * Whether talking to them settles the farm's quest.
   *
   * A flag rather than a name the reducer checks for, so the promise that
   * adding a villager never means touching the reducer survives the one
   * villager who was here before any of this existed.
   */
  questGiver?: boolean;
  /** Item reactions. Anything unlisted falls to `defaultGiftReaction`. */
  gifts: Partial<Record<ItemId, GiftReaction>>;
  defaultGiftReaction: GiftReaction;
  schedule: ScheduleEntry[];
  dialogue: DialogueEntry[];
}

/**
 * The hour a schedule is read against, from 6 to 25.
 *
 * Not `time.hour`, which is a wall clock and wraps: the day runs to 02:00, so
 * `hour` reads 0 and then 1 after midnight and a schedule entry from 21 to 26
 * would stop matching exactly when the village should be asleep. The running
 * total never goes backwards, which is the only property this needs.
 */
export function scheduleHour(time: TimeState): number {
  return Math.floor(time.totalMinutes / 60);
}
