// Generated by scripts/generate-lpc-manifest.mjs from public/assets/lpc/*.png.
// Do not edit by hand: add or remove a PNG in that folder and run
// "npm run lpc:manifest". See public/assets/lpc/CREDITS.md for what the art is
// and what it is licensed under.
import type { CropId } from '../systems/items';

/**
 * Every plain image in the art folder, as [texture key, url].
 *
 * The key is the file name, which is what the scene already called it. A file
 * that is not here is not missing art — the procedural textures in
 * `createPixelArtTextures` stand in for it — so this list is exactly what
 * should be requested over the network, and nothing else.
 */
export const LPC_IMAGES: readonly (readonly [key: string, url: string])[] = [
  ['bush', '/assets/lpc/bush.png'],
  ['crop-cranberry', '/assets/lpc/crop-cranberry.png'],
  ['crop-frostcap', '/assets/lpc/crop-frostcap.png'],
  ['crop-melon', '/assets/lpc/crop-melon.png'],
  ['crop-pumpkin', '/assets/lpc/crop-pumpkin.png'],
  ['crop-rhubarb', '/assets/lpc/crop-rhubarb.png'],
  ['crop-sprout', '/assets/lpc/crop-sprout.png'],
  ['crop-strawberry', '/assets/lpc/crop-strawberry.png'],
  ['crop-sunflower', '/assets/lpc/crop-sunflower.png'],
  ['crop-tomato', '/assets/lpc/crop-tomato.png'],
  ['crop-turnip', '/assets/lpc/crop-turnip.png'],
  ['crop-winterberry', '/assets/lpc/crop-winterberry.png'],
  ['farmhouse', '/assets/lpc/farmhouse.png'],
  ['flowers-gold', '/assets/lpc/flowers-gold.png'],
  ['flowers-red', '/assets/lpc/flowers-red.png'],
  ['flowers-white', '/assets/lpc/flowers-white.png'],
  ['furniture-bed', '/assets/lpc/furniture-bed.png'],
  ['furniture-chair-east', '/assets/lpc/furniture-chair-east.png'],
  ['furniture-chair-west', '/assets/lpc/furniture-chair-west.png'],
  ['furniture-fireplace', '/assets/lpc/furniture-fireplace.png'],
  ['furniture-rug', '/assets/lpc/furniture-rug.png'],
  ['furniture-stove', '/assets/lpc/furniture-stove.png'],
  ['furniture-table', '/assets/lpc/furniture-table.png'],
  ['grass-tuft', '/assets/lpc/grass-tuft.png'],
  ['item-big-chest', '/assets/lpc/item-big-chest.png'],
  ['item-buttercup', '/assets/lpc/item-buttercup.png'],
  ['item-chest', '/assets/lpc/item-chest.png'],
  ['item-chestnut', '/assets/lpc/item-chestnut.png'],
  ['item-churn', '/assets/lpc/item-churn.png'],
  ['item-daffodil', '/assets/lpc/item-daffodil.png'],
  ['item-gravel-path', '/assets/lpc/item-gravel-path.png'],
  ['item-hardwood-fence', '/assets/lpc/item-hardwood-fence.png'],
  ['item-jar', '/assets/lpc/item-jar.png'],
  ['item-keg', '/assets/lpc/item-keg.png'],
  ['item-kiln', '/assets/lpc/item-kiln.png'],
  ['item-perch', '/assets/lpc/item-perch.png'],
  ['item-pike', '/assets/lpc/item-pike.png'],
  ['item-poppy', '/assets/lpc/item-poppy.png'],
  ['item-purple-mushroom', '/assets/lpc/item-purple-mushroom.png'],
  ['item-rainbow-trout', '/assets/lpc/item-rainbow-trout.png'],
  ['item-smallmouth-bass', '/assets/lpc/item-smallmouth-bass.png'],
  ['item-stone-path', '/assets/lpc/item-stone-path.png'],
  ['item-wild-daisy', '/assets/lpc/item-wild-daisy.png'],
  ['item-wild-grape', '/assets/lpc/item-wild-grape.png'],
  ['item-wild-greens', '/assets/lpc/item-wild-greens.png'],
  ['item-wild-leek', '/assets/lpc/item-wild-leek.png'],
  ['item-wood-fence', '/assets/lpc/item-wood-fence.png'],
  ['item-wood-path', '/assets/lpc/item-wood-path.png'],
  ['log', '/assets/lpc/log.png'],
  ['node-forage-buttercup', '/assets/lpc/node-forage-buttercup.png'],
  ['node-forage-chestnut', '/assets/lpc/node-forage-chestnut.png'],
  ['node-forage-daffodil', '/assets/lpc/node-forage-daffodil.png'],
  ['node-forage-poppy', '/assets/lpc/node-forage-poppy.png'],
  ['node-forage-purple-mushroom', '/assets/lpc/node-forage-purple-mushroom.png'],
  ['node-forage-wild-daisy', '/assets/lpc/node-forage-wild-daisy.png'],
  ['node-forage-wild-grape', '/assets/lpc/node-forage-wild-grape.png'],
  ['node-forage-wild-greens', '/assets/lpc/node-forage-wild-greens.png'],
  ['node-forage-wild-leek', '/assets/lpc/node-forage-wild-leek.png'],
  ['node-grass', '/assets/lpc/node-grass.png'],
  ['node-stump', '/assets/lpc/node-stump.png'],
  ['node-tree-0', '/assets/lpc/node-tree-0.png'],
  ['node-tree-1', '/assets/lpc/node-tree-1.png'],
  ['node-tree-2', '/assets/lpc/node-tree-2.png'],
  ['node-tree-3', '/assets/lpc/node-tree-3.png'],
  ['node-tree-4', '/assets/lpc/node-tree-4.png'],
  ['node-weed', '/assets/lpc/node-weed.png'],
  ['placeable-big-chest', '/assets/lpc/placeable-big-chest.png'],
  ['placeable-chest', '/assets/lpc/placeable-chest.png'],
  ['placeable-churn', '/assets/lpc/placeable-churn.png'],
  ['placeable-gravel-path', '/assets/lpc/placeable-gravel-path.png'],
  ['placeable-hardwood-fence', '/assets/lpc/placeable-hardwood-fence.png'],
  ['placeable-jar', '/assets/lpc/placeable-jar.png'],
  ['placeable-keg', '/assets/lpc/placeable-keg.png'],
  ['placeable-kiln', '/assets/lpc/placeable-kiln.png'],
  ['placeable-stone-path', '/assets/lpc/placeable-stone-path.png'],
  ['placeable-wood-fence', '/assets/lpc/placeable-wood-fence.png'],
  ['placeable-wood-path', '/assets/lpc/placeable-wood-path.png'],
  ['plot-tilled', '/assets/lpc/plot-tilled.png'],
  ['plot-tilled-2', '/assets/lpc/plot-tilled-2.png'],
  ['plot-tilled-3', '/assets/lpc/plot-tilled-3.png'],
  ['plot-watered', '/assets/lpc/plot-watered.png'],
  ['plot-watered-2', '/assets/lpc/plot-watered-2.png'],
  ['plot-watered-3', '/assets/lpc/plot-watered-3.png'],
  ['plot-wild', '/assets/lpc/plot-wild.png'],
  ['plot-wild-2', '/assets/lpc/plot-wild-2.png'],
  ['plot-wild-3', '/assets/lpc/plot-wild-3.png'],
  ['stump', '/assets/lpc/stump.png'],
  ['stump-flowers', '/assets/lpc/stump-flowers.png'],
  ['tile-floor-wood', '/assets/lpc/tile-floor-wood.png'],
  ['tile-grass', '/assets/lpc/tile-grass.png'],
  ['tile-grass-1x', '/assets/lpc/tile-grass-1x.png'],
  ['tile-grass-1xy', '/assets/lpc/tile-grass-1xy.png'],
  ['tile-grass-1y', '/assets/lpc/tile-grass-1y.png'],
  ['tile-grass-2', '/assets/lpc/tile-grass-2.png'],
  ['tile-grass-2x', '/assets/lpc/tile-grass-2x.png'],
  ['tile-grass-2xy', '/assets/lpc/tile-grass-2xy.png'],
  ['tile-grass-2y', '/assets/lpc/tile-grass-2y.png'],
  ['tile-grass-3', '/assets/lpc/tile-grass-3.png'],
  ['tile-grass-3x', '/assets/lpc/tile-grass-3x.png'],
  ['tile-grass-3xy', '/assets/lpc/tile-grass-3xy.png'],
  ['tile-grass-3y', '/assets/lpc/tile-grass-3y.png'],
  ['tile-path', '/assets/lpc/tile-path.png'],
  ['tile-wall-bottom', '/assets/lpc/tile-wall-bottom.png'],
  ['tile-wall-bottom-left', '/assets/lpc/tile-wall-bottom-left.png'],
  ['tile-wall-bottom-right', '/assets/lpc/tile-wall-bottom-right.png'],
  ['tile-wall-door-left', '/assets/lpc/tile-wall-door-left.png'],
  ['tile-wall-door-right', '/assets/lpc/tile-wall-door-right.png'],
  ['tile-wall-left', '/assets/lpc/tile-wall-left.png'],
  ['tile-wall-lower-1', '/assets/lpc/tile-wall-lower-1.png'],
  ['tile-wall-lower-2', '/assets/lpc/tile-wall-lower-2.png'],
  ['tile-wall-lower-3', '/assets/lpc/tile-wall-lower-3.png'],
  ['tile-wall-right', '/assets/lpc/tile-wall-right.png'],
  ['tile-wall-upper-1', '/assets/lpc/tile-wall-upper-1.png'],
  ['tile-wall-upper-2', '/assets/lpc/tile-wall-upper-2.png'],
  ['tile-wall-upper-3', '/assets/lpc/tile-wall-upper-3.png'],
  ['tile-water', '/assets/lpc/tile-water.png'],
  ['tile-water-2', '/assets/lpc/tile-water-2.png'],
  ['tile-water-3', '/assets/lpc/tile-water-3.png'],
  ['tree', '/assets/lpc/tree.png'],
  ['tuft-tall', '/assets/lpc/tuft-tall.png'],
];

/**
 * The same images, by key.
 *
 * `LPC_IMAGES` is a list because the loader walks it once at boot.
 * `ItemIcon` in the React panels has the opposite question — "is there a
 * drawing for this one item, and where is it" — and asking that of a list is
 * a scan per cell of the inventory grid.
 *
 * Built from `LPC_IMAGES` rather than written out a second time: every
 * import used to add one line to each list, by hand, and the two could
 * disagree. `Object.fromEntries` of the same pairs cannot.
 */
export const LPC_URL_BY_KEY: Readonly<Record<string, string>> = Object.fromEntries(LPC_IMAGES);

/**
 * The walk sheets, read as nine frames across and four directions down, at
 * 64px each. Row order is the LPC convention: up, left, down, right.
 */
export const LPC_SHEETS = ['player-sheet', 'rowan-sheet'] as const;

/**
 * The animal walk sheets, with the frame size each one was trimmed to.
 *
 * Four frames across and four directions down, in the same row order as the
 * people. The size differs per animal because the art does: a cow needs three
 * times a chicken's box, and padding them all to the largest would put a cow's
 * worth of empty space around every hen — which the game would then measure
 * when it went looking for somewhere to hang a shadow.
 */
export interface LpcAnimalSheet {
  key: string;
  url: string;
  frameWidth: number;
  frameHeight: number;
}

export const LPC_ANIMAL_SHEETS: readonly LpcAnimalSheet[] = [
  { key: 'animal-chicken-sheet', url: '/assets/lpc/animal-chicken-sheet.png', frameWidth: 32, frameHeight: 30 },
  { key: 'animal-cow-sheet', url: '/assets/lpc/animal-cow-sheet.png', frameWidth: 72, frameHeight: 72 },
  { key: 'animal-duck-sheet', url: '/assets/lpc/animal-duck-sheet.png', frameWidth: 32, frameHeight: 30 },
  { key: 'animal-goat-sheet', url: '/assets/lpc/animal-goat-sheet.png', frameWidth: 54, frameHeight: 66 },
];

export type LpcSheet = (typeof LPC_SHEETS)[number];

/**
 * Crops with a hand-drawn ripe sprite. The rest grow the generated plants in
 * `createPixelArtTextures`, which is the arrangement, not a gap to apologise
 * for — but every id that moves out of that fallback and into this list is the
 * game looking more like itself.
 */
export const LPC_CROPS: readonly CropId[] = ['turnip', 'strawberry', 'rhubarb', 'sunflower', 'tomato', 'melon', 'cranberry', 'pumpkin', 'frostcap', 'winterberry'];
