// Generated by scripts/generate-palette-module.mjs from art/palette.json.
// Do not edit by hand: change art/palette.json and run "npm run palette:module".
//
// Every colour the game draws comes from here. A hex literal anywhere in src/
// or scripts/ fails the test in scripts/palette-lock.test.mjs, which is what
// keeps this file meaningful rather than decorative.

/** Every colour in the game, as ramp.step. */
export const PALETTE = {
  'soil.0': '#3a2718',
  'soil.1': '#48331f',
  'soil.2': '#553d27',
  'soil.3': '#63492f',
  'soil.4': '#7d5633',
  'soil.5': '#8f6540',
  'soil.6': '#9d7049',
  'outline.0': '#0f0608',
  'outline.1': '#1f0106',
  'outline.2': '#10111b',
  'outline.3': '#260908',
  'shadow.0': '#281825',
  'shadow.1': '#0a2726',
  'shadow.2': '#2d2330',
  'shadow.3': '#332f66',
  'clothDeep.0': '#3f100b',
  'gold.0': '#c8c05a',
  'gold.1': '#8d8f3a',
  'berry.0': '#7a5a96',
  'foliage.0': '#07391d',
  'foliage.1': '#134507',
  'foliage.2': '#1e413e',
  'foliage.3': '#175819',
  'foliage.4': '#4c4a5d',
  'clothWarm.0': '#841a20',
  'clothWarm.1': '#6b3a24',
  'clothWarm.2': '#a21e34',
  'clothWarm.3': '#943b22',
  'water.0': '#3c49ad',
  'water.1': '#7f2c99',
  'water.2': '#206c9f',
  'water.3': '#1896b3',
  'leaf.0': '#0b6b45',
  'leaf.1': '#3b8115',
  'leaf.2': '#579b2f',
  'leaf.3': '#449a8d',
  'building.0': '#726b7e',
  'building.1': '#b45045',
  'building.2': '#93828d',
  'building.3': '#ef404a',
  'light.0': '#5ea64e',
  'light.1': '#82a204',
  'light.2': '#b78d64',
  'light.3': '#d28560',
  'light.4': '#ff7b3a',
  'light.5': '#eaa473',
  'light.6': '#acbfb0',
  'light.7': '#f8dbbd',
} as const;

/**
 * The name of any colour. A hex string is not a colour; this is.
 *
 * Derived from PALETTE's own keys (`keyof typeof PALETTE`) rather than
 * written out as a second, hand-duplicated list of the same 48 names. Both
 * used to come from one pass over `colours` in this generator, which kept
 * them in sync as long as nobody touched one without the other — but that
 * is a rule a future edit to this file could break without anyone noticing,
 * since a stale union would still typecheck against whatever names remained
 * in PALETTE, just silently reject any name added after it went stale.
 * Deriving the type from the value it names removes the chance to desync.
 */
export type PaletteName = keyof typeof PALETTE;

/** The same colours as a flat list, for the quantiser and the lock test. */
export const PALETTE_HEXES: readonly string[] = Object.values(PALETTE);

/**
 * A colour as the integer Phaser tints with.
 *
 * Phaser wants 0xRRGGBB and the palette stores '#rrggbb'. Converting at the
 * call site is how 0x literals creep back in, so it happens here instead.
 */
export function tint(name: PaletteName): number {
  return Number.parseInt(PALETTE[name].slice(1), 16);
}
