// Generated by scripts/generate-palette-module.mjs from art/palette.json.
// Do not edit by hand: change art/palette.json and run "npm run palette:module".
//
// Every colour the game draws comes from here. A hex literal anywhere in src/
// or scripts/ fails the test in scripts/palette-lock.test.mjs, which is what
// keeps this file meaningful rather than decorative.

/** Every colour in the game, as ramp.step. */
export const PALETTE = {
  'outline.0': '#000000',
  'outline.1': '#160609',
  'outline.2': '#0a131d',
  'outline.3': '#1b0e14',
  'warmDeep.0': '#280707',
  'warmDeep.1': '#370f0b',
  'warmDeep.2': '#45070f',
  'warmDeep.3': '#43180c',
  'shadow.0': '#0c1e24',
  'shadow.1': '#281826',
  'shadow.2': '#082c27',
  'shadow.3': '#2d2330',
  'foliage.0': '#07391d',
  'foliage.1': '#034339',
  'foliage.2': '#134507',
  'foliage.3': '#175819',
  'foliage.4': '#0b6b45',
  'wood.0': '#4c2c14',
  'wood.1': '#602315',
  'wood.2': '#74022d',
  'wood.3': '#494758',
  'clothCool.0': '#352d6a',
  'clothCool.1': '#205062',
  'clothCool.2': '#6b1b8d',
  'clothCool.3': '#3c49ad',
  'clothWarm.0': '#871923',
  'clothWarm.1': '#8f3716',
  'clothWarm.2': '#7a4c2e',
  'clothWarm.3': '#a8463f',
  'clothWarm.4': '#d82a3a',
  'water.0': '#156c98',
  'water.1': '#726b7e',
  'water.2': '#476aca',
  'water.3': '#1a97b3',
  'grass.0': '#387e06',
  'grass.1': '#448c33',
  'grass.2': '#449a8d',
  'grass.3': '#5ea64d',
  'grass.4': '#82a204',
  'earth.0': '#a17049',
  'earth.1': '#c8865a',
  'earth.2': '#fa6353',
  'earth.3': '#be9d83',
  'skin.0': '#e3a77f',
  'skin.1': '#e7d14b',
  'skin.2': '#d0e3cd',
  'skin.3': '#fdd5b7',
  'skin.4': '#f8f3e7',
} as const;

/** The name of any colour. A hex string is not a colour; this is. */
export type PaletteName =
  | 'outline.0'
  | 'outline.1'
  | 'outline.2'
  | 'outline.3'
  | 'warmDeep.0'
  | 'warmDeep.1'
  | 'warmDeep.2'
  | 'warmDeep.3'
  | 'shadow.0'
  | 'shadow.1'
  | 'shadow.2'
  | 'shadow.3'
  | 'foliage.0'
  | 'foliage.1'
  | 'foliage.2'
  | 'foliage.3'
  | 'foliage.4'
  | 'wood.0'
  | 'wood.1'
  | 'wood.2'
  | 'wood.3'
  | 'clothCool.0'
  | 'clothCool.1'
  | 'clothCool.2'
  | 'clothCool.3'
  | 'clothWarm.0'
  | 'clothWarm.1'
  | 'clothWarm.2'
  | 'clothWarm.3'
  | 'clothWarm.4'
  | 'water.0'
  | 'water.1'
  | 'water.2'
  | 'water.3'
  | 'grass.0'
  | 'grass.1'
  | 'grass.2'
  | 'grass.3'
  | 'grass.4'
  | 'earth.0'
  | 'earth.1'
  | 'earth.2'
  | 'earth.3'
  | 'skin.0'
  | 'skin.1'
  | 'skin.2'
  | 'skin.3'
  | 'skin.4';

/** The same colours as a flat list, for the quantiser and the lock test. */
export const PALETTE_HEXES: readonly string[] = Object.values(PALETTE);

/**
 * A colour as the integer Phaser tints with.
 *
 * Phaser wants 0xRRGGBB and the palette stores '#rrggbb'. Converting at the
 * call site is how 0x literals creep back in, so it happens here instead.
 */
export function tint(name: PaletteName): number {
  return Number.parseInt(PALETTE[name].slice(1), 16);
}
