#!/usr/bin/env node
/**
 * Bundles the Tiled maps under `maps/` into a TypeScript module.
 *
 * The client, the server, and the tests all need the same map data. Importing
 * the JSON directly would need import attributes under Node ESM but not under
 * Vite, so the one format every runtime agrees on is a plain TypeScript module.
 * Parsing still happens at runtime in `tiled.ts`; this only carries the bytes.
 *
 * Run after editing a map in Tiled:  npm run maps:build
 */
import fs from 'node:fs';
import path from 'node:path';

const sourceDir = 'maps';
const outFile = path.join('src', 'game', 'world', 'maps.generated.ts');

/** Area id -> Tiled map file. Add a line here when you add an area. */
const AREA_FILES = {
  farm: 'farm.json',
  village: 'village.json',
  forest: 'forest.json',
  farmhouse: 'farmhouse.json',
  plaza: 'plaza.json',
};

function readJson(name) {
  const file = path.join(sourceDir, name);
  if (!fs.existsSync(file)) {
    console.error(`Missing ${file}. Run "npm run maps:seed" to write the starter maps.`);
    process.exit(1);
  }
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

/** Keeps only the fields the parser reads, so the generated file stays small. */
function trimMap(map) {
  return {
    width: map.width,
    height: map.height,
    tilewidth: map.tilewidth,
    tileheight: map.tileheight,
    ...(map.properties ? { properties: map.properties } : {}),
    layers: map.layers
      .filter((layer) => layer.type === 'tilelayer' || layer.type === 'objectgroup')
      .map((layer) =>
        layer.type === 'tilelayer'
          ? { type: layer.type, name: layer.name, width: layer.width, height: layer.height, data: layer.data }
          : {
              type: layer.type,
              name: layer.name,
              objects: layer.objects.map((object) => ({
                id: object.id,
                name: object.name,
                type: object.type,
                x: object.x,
                y: object.y,
                width: object.width,
                height: object.height,
                ...(object.properties ? { properties: object.properties } : {}),
              })),
            },
      ),
  };
}

function trimTileset(tileset) {
  return {
    tilecount: tileset.tilecount,
    tilewidth: tileset.tilewidth,
    tileheight: tileset.tileheight,
    tiles: tileset.tiles.map((tile) => ({
      id: tile.id,
      image: tile.image,
      imagewidth: tile.imagewidth,
      imageheight: tile.imageheight,
      ...(tile.properties ? { properties: tile.properties } : {}),
    })),
  };
}

const tileset = trimTileset(readJson('tileset.json'));
const maps = Object.fromEntries(
  Object.entries(AREA_FILES).map(([id, file]) => [id, trimMap(readJson(file))]),
);

const banner = `// Generated by scripts/build-maps.mjs from maps/*.json. Do not edit by hand:
// edit the Tiled maps and run "npm run maps:build".
import type { TiledMap, TiledTileset } from './tiled';
`;

const body = `
export const TILESET: TiledTileset = ${JSON.stringify(tileset, null, 2)};

export const AREA_IDS = ${JSON.stringify(Object.keys(AREA_FILES))} as const;

export type AreaId = (typeof AREA_IDS)[number];

export const MAP_SOURCES: Record<AreaId, TiledMap> = ${JSON.stringify(maps, null, 2)} as unknown as Record<AreaId, TiledMap>;
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, `${banner}${body}`);

const sizeKb = (fs.statSync(outFile).size / 1024).toFixed(1);
console.log(`wrote ${outFile} (${sizeKb} kB, areas: ${Object.keys(AREA_FILES).join(', ')})`);
