#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { PALETTE } from './lib/palette-data.mjs';

const outDir = path.join('public', 'assets', 'pixel');

/**
 * Two of `quest-star.svg`'s three fills form a ramp — a dark rim, a gold
 * body, and a pale core, nested star inside star inside star — and the same
 * "ramp, not a lone colour" rule from `generate-plot-art.mjs` and
 * `generate-ui.mjs` applies: measuring each fill's own nearest entry in
 * isolation is not enough, because two of the three land on the same one.
 *
 * `#fff2a6` (the pale core) and `#ffd36d` (the gold body) are both nearest
 * to `light.7` (d=0.0752 and d=0.0860). Snapping both would erase the core
 * highlight — the star would read as a two-tone badge, dark rim and flat
 * gold body, with no lit centre. `light.7` is the better fit for `#fff2a6`
 * (0.0752 against `#ffd36d`'s 0.0860), so it stays there; `#ffd36d` moves to
 * its own second-nearest, `light.5` (d=0.1282, a cost of +0.0422 over its
 * unrestricted nearest).
 *
 * `#ffd36d`'s *other* candidate at that step, `light.6` (`#acbfb0`), was
 * rejected on sight, not distance: `light.6` is the pale sage-grey member of
 * the `light` group's "skin, pale foliage, cream" catch-all (see its note in
 * `art/palette.json`), and putting a warm gold highlight there would be the
 * same mistake Task 8 made pinning a grass highlight to a skin tone — a
 * numerically plausible match that reads as the wrong hue on sight. `light.5`
 * (`#eaa473`, a warm peach) keeps the highlight in its own hue family.
 *
 * Both `#ffd36d` and `#fff2a6` are large distances (0.13 and 0.075) for the
 * same reason WILD.bright was in the plot-art generator: this palette's
 * `light` group is desaturated pale tones (cream, skin, sage), and neither
 * literal here is desaturated — they are a saturated gold and a bright pale
 * yellow. There is no tight match for either in a 48-entry palette with no
 * dedicated "saturated highlight" ramp; both are flagged rather than quietly
 * accepted.
 */
const GOLD_RIM = PALETTE['soil.2'];
const GOLD_BODY = PALETTE['light.5'];
const GOLD_CORE = PALETTE['light.7'];

const assets = {
  'quest-star.svg': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" shape-rendering="crispEdges" role="img" aria-label="Quest star icon">
  <rect width="32" height="32" fill="none"/>
  <path fill="${GOLD_RIM}" d="M14 2h4v6h6v4h4v6h-6v6h-4v6h-4v-6H8v-6H2v-6h6V8h6z"/>
  <path fill="${GOLD_BODY}" d="M14 4h4v7h7v4h-7v7h-4v-7H7v-4h7z"/>
  <path fill="${GOLD_CORE}" d="M15 6h2v7h7v2h-7v7h-2v-7H8v-2h7z"/>
</svg>
`,
  // The ribbon's five fills each land on their own genuinely-nearest entry —
  // `soil.2`, `light.3`, `light.5`, `soil.4`, `soil.1` — with no collision
  // among them, so no override was needed here beyond reusing `GOLD_BODY`
  // for the same literal gold (`#ffd36d`) the star uses above. `soil.2`
  // being reused for this ribbon's background (`#5c3723`) and the star's rim
  // above is coincidence, not a ramp: the two SVGs are never composited
  // together, so the two literals converging on one entry costs nothing.
  'market-ribbon.svg': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 32" shape-rendering="crispEdges" role="img" aria-label="Moonberry market ribbon">
  <rect x="0" y="8" width="96" height="18" fill="${PALETTE['soil.2']}"/>
  <rect x="4" y="5" width="88" height="18" fill="${PALETTE['light.3']}"/>
  <rect x="8" y="8" width="80" height="12" fill="${GOLD_BODY}"/>
  <path fill="${PALETTE['soil.4']}" d="M0 8h14v18H0l7-9zM82 8h14l-7 9 7 9H82z"/>
  <text x="48" y="18" text-anchor="middle" font-family="monospace" font-size="8" font-weight="700" fill="${PALETTE['soil.1']}">MOONBERRY</text>
</svg>
`,
};

const provenance = `# Pixel asset provenance\n\nThese SVG support assets are handcrafted deterministic project assets generated by \`scripts/generate-assets.mjs\`. Runtime character, terrain, crop, weather, and UI textures are drawn from code in \`src/game/assets/createPixelArtTextures.ts\` using Phaser canvas textures.\n\n- PixelLab MCP was not used.\n- Assets are original, local/offline, and intentionally avoid direct Stardew Valley lookalikes.\n- License follows the repository license.\n`;

/**
 * Guarded like `generate-plot-art.mjs` and `generate-ui.mjs`. Before this,
 * the whole file ran its writes at module scope, so nothing could `import`
 * it to check its `PALETTE[...]` references without also regenerating the
 * two SVGs and the README as a side effect. See `generate-assets.test.mjs`.
 */
function main() {
  fs.mkdirSync(outDir, { recursive: true });
  for (const [file, content] of Object.entries(assets)) {
    fs.writeFileSync(path.join(outDir, file), content);
    console.log(`wrote ${path.join(outDir, file)}`);
  }

  fs.writeFileSync(path.join(outDir, 'README.md'), provenance);
  console.log(`wrote ${path.join(outDir, 'README.md')}`);
}

if (process.argv[1] && process.argv[1].endsWith('generate-assets.mjs')) {
  main();
}
