#!/usr/bin/env node
/**
 * The wooden frame, drawn once and used by both layers.
 *
 * The panels used to be a web app's idea of a panel — 22px corners, a blurred
 * backdrop, a soft gradient — sitting on top of a pixel-art game. Two visual
 * languages arguing with each other. These are the replacement: square
 * corners, no blur, and a border that is a picture of a plank.
 *
 * They are files rather than canvas drawings because the stylesheet needs one
 * (`border-image`) and the canvas needs one (`this.add.nineslice`), and the
 * point of the exercise is that those two are the same picture.
 */
import fs from 'node:fs';
import path from 'node:path';
import { encodePng, raster } from './lib/png.mjs';

const OUT_DIR = path.join('public', 'assets', 'ui');

/** Deterministic noise, so the grain is the same on every run and in git. */
function hash(x, y, seed = 3) {
  let h = (x * 374761393 + y * 668265263 + seed * 974634211) | 0;
  h = Math.imul(h ^ (h >>> 13), 1274126177);
  return ((h ^ (h >>> 16)) >>> 0) / 4294967295;
}

const WOOD = {
  edge: '#140d08',
  dark: '#3a2516',
  plank: '#6b4429',
  plankLit: '#7d5231',
  plankShade: '#573620',
  rim: '#c9924f',
  rimShade: '#8a5a2e',
  inner: '#241a13',
  fill: '#2b1f18',
};

/**
 * One frame image.
 *
 * `border` is the slice width, and the whole thing is `border * 3` square so
 * the middle slice is a full `border` wide — a one-pixel middle slice is what
 * makes a nine-slice shimmer when the panel it is stretched across is an odd
 * number of pixels wide.
 */
function frame(border, fill) {
  const size = border * 3;
  const { pixels, set } = raster(size, size);

  for (let y = 0; y < size; y += 1) {
    for (let x = 0; x < size; x += 1) {
      const depth = Math.min(x, y, size - 1 - x, size - 1 - y);

      if (depth >= border) {
        set(x, y, fill);
        continue;
      }
      if (depth === 0) {
        set(x, y, WOOD.edge);
        continue;
      }
      if (depth === 1) {
        set(x, y, WOOD.dark);
        continue;
      }
      if (depth === border - 1) {
        set(x, y, WOOD.inner);
        continue;
      }
      if (depth === border - 2) {
        // The lit rim sits one pixel in from the panel, which is what stops
        // the border reading as a flat brown rectangle.
        set(x, y, x < border || y < border ? WOOD.rim : WOOD.rimShade);
        continue;
      }

      // The plank itself: lit towards the top-left, shaded towards the
      // bottom-right, with a grain that runs along the board.
      const lit = x + y < size - 1;
      const grain = hash(Math.floor(x / 2), y) > 0.78 || hash(x, Math.floor(y / 2), 9) > 0.86;
      set(x, y, grain ? WOOD.plankShade : lit ? WOOD.plankLit : WOOD.plank);
    }
  }

  // Corner pegs. Small, and the only thing in the border that is not a plank,
  // so the corners read as joined rather than mitred.
  //
  // Only on the wide frames. On a narrow one the peg would not fit inside the
  // corner slice, and the part of it that spilled into the middle slice would
  // be stretched the length of whatever the frame is wrapped around — a peg
  // smeared into a stripe across an empty inventory cell.
  const peg = Math.max(2, Math.floor(border / 4));
  if (border < 8) return encodePng(size, size, pixels);
  for (const [cx, cy] of [
    [3, 3],
    [size - 3 - peg, 3],
    [3, size - 3 - peg],
    [size - 3 - peg, size - 3 - peg],
  ]) {
    for (let y = 0; y < peg; y += 1) {
      for (let x = 0; x < peg; x += 1) {
        set(cx + x, cy + y, x === 0 || y === 0 ? WOOD.rim : WOOD.rimShade);
      }
    }
  }

  return encodePng(size, size, pixels);
}

const files = {
  // Panels: the satchel, the stall, the forge, the morning summary.
  'frame-wood.png': frame(12, WOOD.fill),
  // Cells: one hotbar slot, one inventory slot. Same wood, a quarter the trim.
  'frame-slot.png': frame(4, '#1f1710'),
  // Bars and readouts that sit directly on the world and must not swallow it.
  'frame-plate.png': frame(6, '#241a14'),
};

fs.mkdirSync(OUT_DIR, { recursive: true });
for (const [file, data] of Object.entries(files)) {
  fs.writeFileSync(path.join(OUT_DIR, file), data);
  console.log(`wrote ${path.join(OUT_DIR, file)} (${data.length} bytes)`);
}

fs.writeFileSync(
  path.join(OUT_DIR, 'README.md'),
  `# Interface frames

Generated by \`scripts/generate-ui.mjs\` — run \`npm run generate:ui\` after editing it.

Original work, drawn from code, no third-party source. Licensed with the repository.

Each file is a nine-slice: a square image whose border is one third of its width.
The stylesheet slices it with \`border-image\`, the canvas with \`this.add.nineslice\`,
and they are the same file on purpose — a border drawn twice is a border that
drifts.

| File | Slice | Used for |
| --- | --- | --- |
| \`frame-wood.png\` | 12px | Panels: satchel, market stall, forge, morning summary |
| \`frame-slot.png\` | 4px | One inventory or hotbar cell |
| \`frame-plate.png\` | 6px | Readouts laid over the world: clock, prompt bar, quest |
`,
);
console.log(`wrote ${path.join(OUT_DIR, 'README.md')}`);
